#-*- mode: ruby -*-

source 'https://rubygems.org'

gem 'leafy-metrics', :path => '../leafy-metrics'
gem 'leafy-health', :path => '../leafy-health'

# for development you do not want to vendor the jars from gem
ENV['JARS_VENDOR'] = 'false'

gemspec

# vim: syntax=Ruby
