#-*- mode: ruby -*-

source 'https://rubygems.org'

gem 'leafy-metrics', :path => '../../leafy-metrics'
gem 'leafy-health', :path => '../../leafy-health'
gem 'leafy-rack', :path => '../../leafy-rack'

gem 'sinatra'

group 'development' do
  gem 'ruby-maven'
  gem 'rake', '~> 10.2'
end
# vim: syntax=Ruby
