#-*- mode: ruby -*-

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new

require "yard"
YARD::Rake::YardocTask.new do |t|
  t.files   = ['lib/**/*.rb']
  t.options += ["--title", "Leafy Metrics API"]
end

task :default => [ :spec ]

# vim: syntax=Ruby
